name: smartnodes
services:
  node-vault:
    image: postgres:latest
    container_name: node-vault
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    env_file:
      - .env
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - pgroot:/var/lib/postgresql
      - ./node-vault:/docker-entrypoint-initdb.d
    restart: unless-stopped
  node-hub:
    image: eclipse-mosquitto:alpine
    container_name: node-hub
    depends_on:
      - node-vault
    environment:
      PGHOST: node-vault
    env_file:
      - .env
    ports:
      - "${HUB_PORT}:${HUB_PORT}"
    volumes:
    - ./node-hub/mosquitto.conf.template:/mosquitto/config/mosquitto.conf.template
    - ./node-hub/mqtt.acl:/mosquitto/config/mqtt.acl
    - ./node-hub/docker-entrypoint.sh:/docker-entrypoint.sh
    - mosquitto_data:/mosquitto/data
    entrypoint: ["/docker-entrypoint.sh"]
    restart: unless-stopped

  node-ingest:
    build: ./node-ingest
    container_name: node-ingest
    depends_on:
      - node-hub
      - node-vault
    environment:
      PGHOST: node-vault
    env_file:
      - .env
    volumes:
      - ./node-ingest/ingest.py:/app/ingest.py
    restart: unless-stopped

  node-gateway:
    build: ./node-gateway
    image: node-gateway
    container_name: node-gateway  
    depends_on:
      - node-vault
    environment:
      PGHOST: node-vault
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - ./node-gateway:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  pgroot: {}