listener 1883
allow_anonymous true
allow_zero_length_clientid true

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/config/dynamic-security.json

sys_interval 10

persistence true
persistence_location /mosquitto/data/

log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true