listener 1883
allow_anonymous true

# Enable SYS stats
sys_interval 10

# Persistence (optional but recommended)
persistence true
persistence_location /mosquitto/data/

# Publish broker log messages as MQTT topics
log_dest topic

# Optional but useful
log_type error
log_type warning
log_type notice
log_type information
connection_messages true