listener 1883
allow_anonymous true

password_file /mosquitto/config/mqtt.pass
acl_file /mosquitto/config/mqtt.acl

sys_interval 10

persistence true
persistence_location /mosquitto/data/

log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true